### ISSUE TITLE
Problem running the training script

### ISSUE THREAD

**Issue by rreddy78** [Tsinghua-MARS-Lab/HDMapNet#55]
Hi Authors,

I have a Conda 3.10 Env with packages as follows with all required packages:

But when I run the training command I get this error:

(hdmapnet) sxv1kor@BMH7160115:~/Downloads/HDMapNet$ python train.py --instance_seg --direction_pred  --logdir ./logdir/
Traceback (most recent call last):
  File "/home/sxv1kor/Downloads/HDMapNet/train.py", line 193, in <module>
    train(args)
  File "/home/sxv1kor/Downloads/HDMapNet/train.py", line 53, in train
    model = get_model(args.model, data_conf, args.instance_seg, args.embedding_dim, args.direction_pred, args.angle_class)
  File "/home/sxv1kor/Downloads/HDMapNet/model/__init__.py", line 10, in get_model
    model = HDMapNet(data_conf, instance_seg=instance_seg, embedded_dim=embedded_dim, direction_pred=direction_pred, direction_dim=angle_class, lidar=False)
  File "/home/sxv1kor/Downloads/HDMapNet/model/hdmapnet.py", line 46, in __init__
    dx, bx, nx = gen_dx_bx(data_conf['xbound'], data_conf['ybound'], data_conf['zbound'])
  File "/home/sxv1kor/Downloads/HDMapNet/data/utils.py", line 40, in gen_dx_bx
    nx = torch.LongTensor([(row[1] - row[0]) / row[2] for row in [xbound, ybound, zbound]])
TypeError: 'float' object cannot be interpreted as an integer

**Comment by BEV-DAR** [comment]
I met the same problem, did u solve it? Thx
